version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: makarna62
      MYSQL_DATABASE: spiny-database
      MYSQL_PASSWORD: makarna62
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql-scripts/01-spiny-directory.sql:/docker-entrypoint-initdb.d/01-spiny-directory.sql

  web:
    container_name: web
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      db_url: jdbc:mysql://mysql:3306/spiny-database
    depends_on:
      - mysql
    restart: on-failure:10

volumes:
  mysql_data:
